image: 'hub.weibo.cn/h5/runner'
before_script:
  - 'yarn install'
lint:
  tags:
    - HTML5
  only:
    - branches
  script:
    - 'npm run lint'
deploy:
  environment: production
  tags:
    - HTML5
  only:
    - tags@html5/v-annual-report
  script:
    - 'npm run deploy'
    - 'rm $CI_PROJECT_DIR/dist/index.html'
    - 'cat $CI_PROJECT_DIR/webpack-assets.json'
    - 'push2cdn --m=h5_sinaimg_m --pre=v-annual-report --src=$CI_PROJECT_DIR/dist'
    - 'update_version'
  artifacts:
    paths:
      - dist/
